/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as ClientProfileRouteImport } from './routes/client.profile'
import { Route as ClientActivityRouteImport } from './routes/client.activity'
import { Route as ClientRecommendationIdRouteImport } from './routes/client.recommendation.$id'
import { Route as ClientProductIdRouteImport } from './routes/client.product.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/client/profile',
  path: '/client/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientActivityRoute = ClientActivityRouteImport.update({
  id: '/client/activity',
  path: '/client/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRecommendationIdRoute = ClientRecommendationIdRouteImport.update({
  id: '/client/recommendation/$id',
  path: '/client/recommendation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProductIdRoute = ClientProductIdRouteImport.update({
  id: '/client/product/$id',
  path: '/client/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client/activity': typeof ClientActivityRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/': typeof ClientIndexRoute
  '/client/product/$id': typeof ClientProductIdRoute
  '/client/recommendation/$id': typeof ClientRecommendationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client/activity': typeof ClientActivityRoute
  '/client/profile': typeof ClientProfileRoute
  '/client': typeof ClientIndexRoute
  '/client/product/$id': typeof ClientProductIdRoute
  '/client/recommendation/$id': typeof ClientRecommendationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client/activity': typeof ClientActivityRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/': typeof ClientIndexRoute
  '/client/product/$id': typeof ClientProductIdRoute
  '/client/recommendation/$id': typeof ClientRecommendationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client/activity'
    | '/client/profile'
    | '/client/'
    | '/client/product/$id'
    | '/client/recommendation/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client/activity'
    | '/client/profile'
    | '/client'
    | '/client/product/$id'
    | '/client/recommendation/$id'
  id:
    | '__root__'
    | '/'
    | '/client/activity'
    | '/client/profile'
    | '/client/'
    | '/client/product/$id'
    | '/client/recommendation/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientActivityRoute: typeof ClientActivityRoute
  ClientProfileRoute: typeof ClientProfileRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ClientProductIdRoute: typeof ClientProductIdRoute
  ClientRecommendationIdRoute: typeof ClientRecommendationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/client/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/activity': {
      id: '/client/activity'
      path: '/client/activity'
      fullPath: '/client/activity'
      preLoaderRoute: typeof ClientActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/recommendation/$id': {
      id: '/client/recommendation/$id'
      path: '/client/recommendation/$id'
      fullPath: '/client/recommendation/$id'
      preLoaderRoute: typeof ClientRecommendationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/product/$id': {
      id: '/client/product/$id'
      path: '/client/product/$id'
      fullPath: '/client/product/$id'
      preLoaderRoute: typeof ClientProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientActivityRoute: ClientActivityRoute,
  ClientProfileRoute: ClientProfileRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientProductIdRoute: ClientProductIdRoute,
  ClientRecommendationIdRoute: ClientRecommendationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
